application: proyecto-als-opbaquero
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates
  application_readable: true

- url: /res
  static_dir: res

- url: /error
  script: src.handlers.error.app

- url: /manage_client
  script: src.handlers.manage_client.app
  login: required

- url: /clients/add
  script: src.handlers.client.add.app
  login: required

- url: /motorcycle/add
  script: src.handlers.motorcycle.add.app
  login: required

- url: /repair/add
  script: src.handlers.repair.add.app
  login: required

- url: /clients/modify
  script: src.handlers.client.modify.app
  login: required

- url: /motorcycle/modify
  script: src.handlers.motorcycle.modify.app
  login: required

- url: /repair/modify
  script: src.handlers.repair.modify.app
  login: required

- url: /clients/delete
  script: src.handlers.client.delete.app
  login: required

- url: /motorcycle/delete
  script: src.handlers.motorcycle.delete.app
  login: required

- url: /repair/delete
  script: src.handlers.repair.delete.app
  login: required

- url: /
  script: src.handlers.welcome.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
